import type { Metadata } from "next";
import "./globals.css";

import fontVariables from "@/styles/fonts";
import Theme from "@/utils/themeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontVariables} antialiased`}>
          <Theme>
            {children}
          </Theme>
      </body>
    </html>
  );
}
