name: publish-to-github-pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      NEXT_PUBLIC_CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js 🏗️
        run: |
          if [ -f next.config.js ]; then
            echo "⚠️ Found next.config.js - Deleting it..."
            rm next.config.js
          fi

          # Build with production environment
          NODE_ENV=production npx next build

          # Ensure public files are copied
          echo "📁 Copying public files to out directory..."
          cp -r public/* out/

          # Verify build contents
          echo "✅ Out folder contents:"
          ls -R out/
        working-directory: .

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Verify Built Images
        run: |
          echo "📷 Checking images in out folder:"
          find out -type f \( -name "*.svg" -o -name "*.png" -o -name "*.jpg" -o -name "*.webp" \)
          echo "🌐 Checking image paths in HTML:"
          grep -r "src=" out/ || true

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
